# Generated by Django 2.2 on 2021-01-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0002_comment_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='original_quoter',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
