# Generated by Django 2.2 on 2021-01-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0003_auto_20210119_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='solo_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
